---
# defaults file for powerflex_sdr
file_glob_name: sdr
file_gpg_name: RPM-GPG-KEY-ScaleIO
powerflex_common_file_install_location: "/var/tmp"
powerflex_sdr_repl_journal_capacity_max_ratio: 10
powerflex_role_environment:
  MDM_IP: "{{ powerflex_sdr_mdm_primary_ip }}"
powerflex_sdr_state: present
