---
- name: SDS uninstallation
  hosts: sds
  vars_files:
    - ../../../../playbooks/roles/vars_files/connection.yml
  tasks:
    - name: Uninstall powerflex SDS
      register: powerflex_sds_uninstall_outputs
      ansible.builtin.import_role:
        name: powerflex_sds
      vars:
        powerflex_sds_state: absent

    - name: Verifying uninstall package in check mode
      ansible.builtin.assert:
        that:
          - 'powerflex_sds_uninstall_output.results[0].rc == 0'
          - 'powerflex_sds_uninstall_output.changed'
      when: ansible_check_mode

    - name: Verifying remove the sds in normal mode
      ansible.builtin.assert:
        that:
          - 'powerflex_sds_remove_result.sds_details == None'
      when:
        - not ansible_check_mode
        - powerflex_sds_remove_result.changed

    - name: Verifying remove the sds in check mode
      ansible.builtin.assert:
        that:
          - 'powerflex_sds_remove_result.changed'
      when: ansible_check_mode
