---
galaxy_info:
  author: Jennifer John
  description: The role helps to manage the common functions of PowerFlex.
  company: Dell Technologies
  role_name: powerflex_common
  namespace: dellemc
  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  # Choose a valid license ID from https://spdx.org - some suggested licenses:
  # - BSD-3-Clause (default)
  # - MIT
  # - GPL-2.0-or-later
  # - GPL-3.0-only
  # - CC-BY-4.0
  license: GPL-3.0-only

  min_ansible_version: "2.14.0"
  platforms:
    - name: EL
      versions:
        - "9"
        - "8"
    - name: Ubuntu
      versions:
        - jammy
    - name: SLES
      versions:
        - "15SP3"
        - "15SP4"

  galaxy_tags: []
  # List tags for your role here, one per line. A tag is a keyword that describes
  # and categorizes the role. Users find roles by searching for tags. Be sure to
  # remove the '[]' above, if you add tags to this list.
  #
  # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
  #       Maximum 20 tags per role.
