---
provisioner:
  name: ansible
  inventory:
    links:
      hosts: ../../../../playbooks/roles/inventory
      group_vars: ../../../../playbooks/roles/group_vars/
      host_vars: ../../../../playbooks/roles/host_vars/
scenario:
  test_sequence:
    - converge
