---
- name: Converge
  hosts: sdc
  vars_files:
    - ../../../../playbooks/roles/vars_files/connection.yml
  gather_facts: false
  tasks:
    - name: "Install and configure powerflex SDC with wrong SDC IP"
      ansible.builtin.import_role:
        name: "powerflex_sdc"
      vars:
        powerflex_sdc_state: present
      ignore_unreachable: true
      ignore_errors: true
      register: powerflex_sdc_wrong_ip_output
